### ISSUE TITLE
سلام امکانش هست یه توضیح مختصر در مورد روش هاش بدید

### ISSUE THREAD

**Issue by ramtiny** [Ptechgithub/Gost#1]
سلام و خسته نباشید 
ممنون بابت اینکه کار رو برای ما آسون کردید و زحمت اسکریپت با شما هست
توضیحاتتون یجا آوردید 
روش اول فقط روی سرور داخلی(ایران) اجرا میشه.
باقی روش ها روی هردو سرور ( داخلی - خارجی ) اجرا کنید.

ما روش اول رو باید اجرا کنیم یا روش دوم
خواستم بدونم فرق هاشون چیه
و مورد بعدی اینکه منظور از relay+ws چیه ؟
آیا گاست هم مثل ریورس ورژن های مختلف داره؟ یااینکه استیبل هست؟
تشکر

**Comment by Ptechgithub** [comment]
سلام 
شما به 5 روش میتونید بین دو سرور تانل بزنید روش اول فقط روی سرور ایران اجرا میشه و نیازی نیست روی سرور خارج اجرا بشه.
هر روش از یک انکریپشن برتی انتقال دینا استفاده میکنه‌. 
و شما برحسب نیاز خودتون هر کدومو که خواستید استفاده کنید.
وقتی سوال میپرسه پورت کانکشن سرور . یعنی پورتی که دوتا سرور با هم ارتباط میگیرن. 
و پورت کانفیگ هم که مشخصه پورت کانفیگتون رو وارد کنید .
جایی که میپرسه tcp یا udp اگه از پروتکل هایی که بر پایه udp است مثل wireguard از udp استفاده کنید.
