### ISSUE TITLE
گوست همراه با sni

### ISSUE THREAD

**Issue by masoudgb** [Ptechgithub/Gost#4]
سلام
ممنون بابت این اسکریپت عالی
پیشنهاد اول اضافه کردن sni
پیشنهاد دوم امکان اضافه کردن پورت در سرور خارج چون این امکان فقط برای سرور ایران وجود دارد
با احترام 🙏

**Comment by Ptechgithub** [comment]
سلام 🌹
حالت های زیادی داره که چند تاشو گذاشتم شلوغ نشه.
میتونید از  custom استفاده کنید.

**Comment by masoudgb** [comment]
سپاسگذارم پیمان عزیز
